// Replace with your unique name
exports.appName = 'LoopBackPushNotificationDemoApplication';

// Use your own Server Key as generated by Google Developer Console
// For more details, see http://developer.android.com/google/gcm/gs.html
exports.gcmServerApiKey = 'Your-server-api-key';

// You may want to use your own credentials here
exports.apnsTokenKeyPath = './server/private/notification/apns.p8';
exports.apnsTokenKeyId = 'xxxxxxxx';
exports.apnsTokenTeamId = 'xxxxxxxx';
exports.apnsBundleId = 'com.company.app';
